version: "3"

services:
  client:
    # build:
    #   context: ./client
    #   dockerfile: Dockerfile.dev
    image: lowertask-dev/client
    ports:
      - 3001:3000
    volumes:
      - "./src:/app/src"
    
