version: "3"

services:
  api:
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile.dev
    # image: lowertask-dev/backend
    image: lowertask-devwatch/backend
    ports:
      - "5000:3001"
    depends_on:
      - mongo-db
    environment:
      - PORT=3001
      - NODE_ENV=DEV
      - DEV_MONGO_PORT=27017
      - DEV_MONGO_HOST=db
      - DEV_MONGO_DBNAME=taskapp
      - DEV_MONGO_USER=
      - DEV_MONGO_PASSWORD=
    volumes:
      - "./backend/src:/app/src"
  mongo-db:
    container_name: db
    image: mongo
    volumes:
      - "./db:/data/db"
