version: "3" # optional since v1.27.0

services:
  api:
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile.dev
    image: lowertask/backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo-db
    environment:
      - PORT=5000
      - MONGO_PORT=27017
      - MONGO_HOST=db
      - MONGO_DBNAME=lowertaskdb
      - MONGO_USER=
      - MONGO_PASSWORD=
  # mongo-db:
  #   container_name: db
  #   image: mongo
  #   volumes:
  #     - "./db:/data/db"
