version: "3"

services:
  api:
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile.dev
    image: lowertask-dev/backend
    container_name: api
    ports:
      - "5001:5000"
    depends_on:
      - mongo-db
    environment:
      - PORT=5000
      - NODE_ENV=DEV
      - DEV_MONGO_PORT=27017
      - DEV_MONGO_HOST=db
      - DEV_MONGO_DBNAME=taskapp
      - DEV_MONGO_USER=
      - DEV_MONGO_PASSWORD=
      - FILE_STORAGE_NAME=lower-task-image-bucket 
      - FILE_STORAGE_ENDPOINT=http://minio:9000
      - FILE_STORAGE_ACCESS_KEY=minioadmin
      - FILE_STORAGE_SECRET_ACCESS=minioadmin
    volumes:
      - "./backend/src:/app/src"
  object-storage:
    image: minio/minio
    container_name: minio 
    ports:
      - "9000:9000"
    volumes:
      - ./db/minio:/data
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data
  client:
    # build:
    #   context: ./client
    #   dockerfile: Dockerfile.dev
    image: lowertask-dev/client
    ports:
      - 3001:3000
    environment:
      - REACT_APP_TASK_API_KEY=asd
      - REACT_APP_AUTH_API_KEY=asd
      - REACT_APP_NO_SECRET=somecode
    volumes:
    - "./client/src:/app/src"
  mongo-db:
    container_name: db
    image: mongo
    volumes:
      - "./db:/data/db"
