version: "3"

services:
  api:
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile.dev
    image: lowertask-dev/backend
    container_name: api
    ports:
      - "5001:5000"
    depends_on:
      - mongo-db
    environment:
      - PORT=5000
      - NODE_ENV=DEV
      - DEV_MONGO_PORT=27017
      - DEV_MONGO_HOST=db
      - DEV_MONGO_DBNAME=taskapp
      - DEV_MONGO_USER=
      - DEV_MONGO_PASSWORD=
    volumes:
      - "./backend/src:/app/src"
  client:
    # build:
    #   context: ./client
    #   dockerfile: Dockerfile.dev
    image: lowertask-dev/client
    ports:
      - 3001:3000
    environment:
      - REACT_APP_TASK_API_KEY=http://localhost:5001
      - REACT_APP_AUTH_API_KEY=http://localhost:5001
    volumes:
      - "./client/src:/app/src"
  mongo-db:
    container_name: db
    image: mongo
    volumes:
      - "./db:/data/db"
