version: "3"

services:
  api:
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile.dev
    image: lowertask/backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_PORT=27017
      - MONGO_HOST=db
      - MONGO_DBNAME=lowertaskdb
      - MONGO_USER=
      - MONGO_PASSWORD=
